name: Java Maven Build for the SpringBoot Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java 11
      - id: get-version
        name: mvn build
        uses: jactions/maven-version@v1

      # Run Maven clean install
      - name: Build with Maven
        run: mvn clean install

