name: Java Maven Build for the SpringBoot Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java 11
      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adoptium'

      # Set up Maven 3.8.1
      - name: Set up Maven 3.8.1
        uses: actions/setup-java@v3
        with:
          maven-version: '3.8.1'
          java-version: '11'

      # Run Maven clean install
      - name: Build with Maven
        run: mvn clean install

