name: Java Maven Build for the SpringBoot Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3
      
      - uses: actions/checkout@v4
      - name: Java Build
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - name: Set up Maven
        uses: hb0730/maven-action@latest
        with:
          maven-version: 3.8.2
          maven-file: ${{ runner.temp }}/apache-maven-3.8.2-bin.tar.gz
          url: https://downloads.apache.org/maven/maven-3/3.8.2/binaries/apache-maven-3.8.2-bin.tar.gz  

      # Set up Java 11
      - id: get-version
        name: mvn build
        uses: jactions/maven-version@v1

      # Run Maven clean install
      - name: Build with Maven
        run: mvn clean install

