name: Java Maven Build for the SpringBoot Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven (verify)
        run: mvn --batch-mode --update-snapshots verify

      - name: Build with Maven (clean install)
        run: mvn clean install
      # Step 4: Upload the JAR file as an artifact
      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v3
        with:
          name: spring-boot-mongo-jar
          path: target/spring-boot-mongo-1.0.jar
      - name: Do Something with Artifact
        run: |
            ls /home/runner/work/actions-java-project/actions-java-project/target