name: Echo Environment Variables

on:
  push:
    branches:
      - main

jobs:
  echo-environment-vars:
    runs-on: ubuntu-latest
    
    # Use environment context to reference each environment
    steps:
      - name: Print Environment Variables for Dev
        environment: dev  # Defines the environment for this step
        run: |
          echo "Environment: Dev"
          echo "USER=${{ github.env.USER }}"
          echo "API_KEY=${{ github.env.API_KEY }}"

      - name: Print Environment Variables for Test
        environment: test  # Defines the environment for this step
        run: |
          echo "Environment: Test"
          echo "USER=${{ github.env.USER }}"
          echo "API_KEY=${{ github.env.API_KEY }}"

      - name: Print Environment Variables for Prod
        environment: prod  # Defines the environment for this step
        run: |
          echo "Environment: Prod"
          echo "USER=${{ github.env.USER }}"
          echo "API_KEY=${{ github.env.API_KEY }}"
