name: Echo Environment Variables

on:
  push:
    branches:
      - main

jobs:
  echo-environment-vars:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, test, prod]

    steps:
      - name: Print Environment Variables
        env:
          USER: ${{ secrets[matrix.environment + '_USER'] }}
          API_KEY: ${{ secrets[matrix.environment + '_API_KEY'] }}
        run: |
          echo "Environment: ${{ matrix.environment }}"
          echo "USER=$USER"
          echo "API_KEY=$API_KEY"
