name: Echo Environment Variables

on:
  push:
    branches:
      - main

jobs:
  echo-environment-vars:
    runs-on: ubuntu-latest

    steps:
      - name: Print Environment Variables for Dev
        env:
          USER: ${{ vars.USER }}
          API_KEY: ${{ vars.API_KEY }}
        run: |
          echo "Environment: Dev"
          echo "USER=$USER"
          echo "API_KEY=$API_KEY"

      - name: Print Environment Variables for Test
        env:
          USER: ${{ vars.USER }}
          API_KEY: ${{ vars.API_KEY }}
        run: |
          echo "Environment: Test"
          echo "USER=$USER"
          echo "API_KEY=$API_KEY"

      - name: Print Environment Variables for Prod
        env:
          USER: ${{ vars.USER }}
          API_KEY: ${{ vars.API_KEY }}
        run: |
          echo "Environment: Prod"
          echo "USER=$USER"
          echo "API_KEY=$API_KEY"

