name: Echo Environment Variables

on:
  push:
    branches:
      - main

jobs:
  echo-environment-vars:
    runs-on: ubuntu-latest

    steps:
      - name: Print Environment Variables for Dev
        environment: dev
        run: |
          echo "Environment: Dev"
          echo "USER=${{ vars.dev_USER }}"
          echo "API_KEY=${{ vars.dev_API_KEY }}"

      - name: Print Environment Variables for Test
        environment: test
        run: |
          echo "Environment: Test"
          echo "USER=${{ vars.test_USER }}"
          echo "API_KEY=${{ vars.test_API_KEY }}"

      - name: Print Environment Variables for Prod
        environment: prod
        run: |
          echo "Environment: Prod"
          echo "USER=${{ vars.prod_USER }}"
          echo "API_KEY=${{ vars.prod_API_KEY }}"
