name: Echo Environment Variables

on:
  push:
    branches:
      - main

jobs:
  echo-environment-vars-dev:
    runs-on: ubuntu-latest
    environment: dev  # Link this job to the 'dev' environment
    steps:
      - name: Print Environment Variables for Dev
        run: |
          echo "Environment: Dev"
          echo "USER=${{ env.USER }}"
          echo "API_KEY=${{ env.API_KEY }}"

  echo-environment-vars-test:
    runs-on: ubuntu-latest
    environment: test  # Link this job to the 'test' environment
    steps:
      - name: Print Environment Variables for Test
        run: |
          echo "Environment: Test"
          echo "USER=${{ env.USER }}"
          echo "API_KEY=${{ env.API_KEY }}"

  echo-environment-vars-prod:
    runs-on: ubuntu-latest
    environment: prod  # Link this job to the 'prod' environment
    steps:
      - name: Print Environment Variables for Prod
        run: |
          echo "Environment: Prod"
          echo "USER=${{ env.USER }}"
          echo "API_KEY=${{ env.API_KEY }}"
