name: Echo Environment Variables

on:
  push:
    branches:
      - main

jobs:
  echo-environment-vars:
    runs-on: ubuntu-latest
    environment: dev  # Specify the environment for the job here
    
    steps:
      - name: Print Environment Variables for Dev
        run: |
          echo "Environment: Dev"
          echo "USER=${{ secrets.USER }}"
          echo "API_KEY=${{ secrets.API_KEY }}"

  echo-environment-vars-test:
    runs-on: ubuntu-latest
    environment: test  # Specify the environment for the job here
    
    steps:
      - name: Print Environment Variables for Test
        run: |
          echo "Environment: Test"
          echo "USER=${{ secrets.USER }}"
          echo "API_KEY=${{ secrets.API_KEY }}"

  echo-environment-vars-prod:
    runs-on: ubuntu-latest
    environment: prod  # Specify the environment for the job here
    
    steps:
      - name: Print Environment Variables for Prod
        run: |
          echo "Environment: Prod"
          echo "USER=${{ secrets.USER }}"
          echo "API_KEY=${{ secrets.API_KEY }}"
