name: Echo Environment Variables

on:
  push:
    branches:
      - main

jobs:
  echo-environment-vars-dev:
    runs-on: ubuntu-latest
    environment: dev  # Link this job to the 'dev' environment
    steps:
      - name: Print Environment Variables for Dev
        run: |
          echo "Repository Name: ${{ github.repository }}"
          echo "Debugging Mode: Step Debug = $ACTIONS_STEP_DEBUG, Runner Debug = $ACTIONS_RUNNER_DEBUG"
          echo "Branch Name: ${{ github.ref_name }}" 
          echo "Event Name: ${{ github.event_name }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Environment: Dev"
          echo "This is the key of $USER"
          echo "This is key of $API_KEY" 
          echo $?
          echo "This variables $GITHUB_ACTION is $GITHUB_WORKFLOW  $GITHUB_REPOSITORY"

  echo-environment-vars-test:
    runs-on: ubuntu-latest
    environment: test  # Link this job to the 'test' environment
    steps:
      - name: Print Environment Variables for Test
        run: |
          echo "Environment: Test"
          echo "This variables $GITHUB_ACTION"
          echo "This is the key of $USER"
          echo "This is key of $API_KEY"

  echo-environment-vars-prod:
    runs-on: ubuntu-latest
    environment: prod  # Link this job to the 'prod' environment
    steps:
      - name: Print Environment Variables for Prod
        run: |
          echo "Environment: Prod"
          echo "This is the key of $USER"
          echo "This is key of $API_KEY"