name: Echo Environment Variables

on:
  push:
    branches:
      - main

jobs:
  echo-environment-vars:
    runs-on: ubuntu-latest

    steps:
      - name: Print Environment Variables for Dev
        environment: dev
        run: |
          echo "Environment: Dev"
          echo "USER=${{ secrets.USER }}"
          echo "API_KEY=${{ secrets.API_KEY }}"

      - name: Print Environment Variables for Test
        environment: test
        run: |
          echo "Environment: Test"
          echo "USER=${{ secrets.USER }}"
          echo "API_KEY=${{ secrets.API_KEY }}"

      - name: Print Environment Variables for Prod
        environment: prod
        run: |
          echo "Environment: Prod"
          echo "USER=${{ secrets.USER }}"
          echo "API_KEY=${{ secrets.API_KEY }}"
